version: "3"
services:

  redis:
    image: redis:alpine
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 80
    networks:
      - traefik_public
      - backend
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=traefik_public
        - traefik.frontend.rule=Host:vote.vshipp.com
        - traefik.port=80
  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 80
    networks:
      - traefik_public
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=traefik_public
        - traefik.frontend.rule=Host:result.vshipp.com
        - traefik.port=80

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - traefik_public
      - backend
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=VOTING]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    networks:
      - traefik_public
      - backend
    ports:
      - "8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.docker.network=traefik_public
        - traefik.frontend.rule=Host:visual.vshipp.com
        - traefik.port=9090

networks:
  backend:
    driver: overlay
  traefik_public:
    external: true
volumes:
  db-data:
